Fixed auto-compilation framework
git-svn-id: https://omxil.svn.sourceforge.net/svnroot/omxil/branches/inheritance_branch@108 d11a7513-620d-0410-9d76-e80dcb6a9808

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -463,7 +463,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL WITH_ALSASINK_TRUE WITH_ALSASINK_FALSE WITH_FFMPEGLIBRARY_TRUE WITH_FFMPEGLIBRARY_FALSE WITH_FFMPEGCOMPONENTS_TRUE WITH_FFMPEGCOMPONENTS_FALSE WITH_ALSACOMPONENT_TRUE WITH_ALSACOMPONENT_FALSE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE build build_cpu build_vendor build_os host host_cpu host_vendor host_os EGREP LN_S ECHO AR ac_ct_AR RANLIB ac_ct_RANLIB CPP CXX CXXFLAGS ac_ct_CXX CXXDEPMODE am__fastdepCXX_TRUE am__fastdepCXX_FALSE CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL WITH_ALSASINK_TRUE WITH_ALSASINK_FALSE WITH_FFMPEGLIBRARY_TRUE WITH_FFMPEGLIBRARY_FALSE WITH_FFMPEGCOMPONENTS_TRUE WITH_FFMPEGCOMPONENTS_FALSE WITH_ALSACOMPONENT_TRUE WITH_ALSACOMPONENT_FALSE WITH_AUDIOEFFECTS_TRUE WITH_AUDIOEFFECTS_FALSE LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1035,6 +1035,8 @@ Optional Features:
   --disable-ffmpegcomponents
                           whether to disable ffmpeg components compilation
   --disable-alsacomponent whether to disable alsa component compilation
+  --disable-audioeffects  whether to disable the audio effects components
+                          compilation
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -3644,7 +3646,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3647 "configure"' > conftest.$ac_ext
+  echo '#line 3649 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5223,7 +5225,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:5226:" \
+echo "$as_me:5228:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -6321,11 +6323,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6324: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6326: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6328: \$? = $ac_status" >&5
+   echo "$as_me:6330: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6583,11 +6585,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6586: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6588: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6590: \$? = $ac_status" >&5
+   echo "$as_me:6592: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -6645,11 +6647,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6648: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6650: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6652: \$? = $ac_status" >&5
+   echo "$as_me:6654: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -8030,7 +8032,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 8033 "configure"' > conftest.$ac_ext
+    echo '#line 8035 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -8901,7 +8903,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8904 "configure"
+#line 8906 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8999,7 +9001,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9002 "configure"
+#line 9004 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11247,11 +11249,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11250: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11252: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11254: \$? = $ac_status" >&5
+   echo "$as_me:11256: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -11309,11 +11311,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11312: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11314: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11316: \$? = $ac_status" >&5
+   echo "$as_me:11318: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11824,7 +11826,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 11827 "configure"' > conftest.$ac_ext
+    echo '#line 11829 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -12695,7 +12697,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12698 "configure"
+#line 12700 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12793,7 +12795,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12796 "configure"
+#line 12798 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13678,11 +13680,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13681: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13683: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13685: \$? = $ac_status" >&5
+   echo "$as_me:13687: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -13740,11 +13742,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13743: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13745: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13747: \$? = $ac_status" >&5
+   echo "$as_me:13749: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15105,7 +15107,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 15108 "configure"' > conftest.$ac_ext
+    echo '#line 15110 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -15878,11 +15880,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15881: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15883: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15885: \$? = $ac_status" >&5
+   echo "$as_me:15887: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16140,11 +16142,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16143: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16145: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16147: \$? = $ac_status" >&5
+   echo "$as_me:16149: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16202,11 +16204,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16205: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16207: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16209: \$? = $ac_status" >&5
+   echo "$as_me:16211: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -17587,7 +17589,7 @@ linux*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*|powerpc64*)
-    echo '#line 17590 "configure"' > conftest.$ac_ext
+    echo '#line 17592 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -18458,7 +18460,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18461 "configure"
+#line 18463 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18556,7 +18558,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18559 "configure"
+#line 18561 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -20323,7 +20325,25 @@ else
 fi
 
 
-                                                                                                                        ac_config_files="$ac_config_files Makefile include/Makefile src/Makefile src/base/Makefile src/components/Makefile src/components/alsa/Makefile src/components/ffmpeg/Makefile src/components/audio_effects/Makefile test/Makefile test/components/Makefile test/components/alsasink/Makefile test/components/ffmpeg/Makefile"
+#Check whether alsa component has been requested
+# Check whether --enable-audioeffects or --disable-audioeffects was given.
+if test "${enable_audioeffects+set}" = set; then
+  enableval="$enable_audioeffects"
+  with_audioeffects=false
+else
+  with_audioeffects=true
+fi;
+
+if test x$with_audioeffects = xtrue; then
+  WITH_AUDIOEFFECTS_TRUE=
+  WITH_AUDIOEFFECTS_FALSE='#'
+else
+  WITH_AUDIOEFFECTS_TRUE='#'
+  WITH_AUDIOEFFECTS_FALSE=
+fi
+
+
+                                                                                                                                  ac_config_files="$ac_config_files Makefile include/Makefile src/Makefile src/base/Makefile src/components/Makefile src/components/alsa/Makefile src/components/ffmpeg/Makefile src/components/audio_effects/Makefile test/Makefile test/components/Makefile test/components/alsasink/Makefile test/components/audio_effects/Makefile test/components/ffmpeg/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -20492,6 +20512,13 @@ if test -z "${WITH_ALSACOMPONENT_TRUE}" && test -z "${WITH_ALSACOMPONENT_FALSE}"
   { { echo "$as_me:$LINENO: error: conditional \"WITH_ALSACOMPONENT\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"WITH_ALSACOMPONENT\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${WITH_AUDIOEFFECTS_TRUE}" && test -z "${WITH_AUDIOEFFECTS_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"WITH_AUDIOEFFECTS\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"WITH_AUDIOEFFECTS\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -20945,6 +20972,7 @@ do
   "test/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/Makefile" ;;
   "test/components/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/components/Makefile" ;;
   "test/components/alsasink/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/components/alsasink/Makefile" ;;
+  "test/components/audio_effects/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/components/audio_effects/Makefile" ;;
   "test/components/ffmpeg/Makefile" ) CONFIG_FILES="$CONFIG_FILES test/components/ffmpeg/Makefile" ;;
   "depfiles" ) CONFIG_COMMANDS="$CONFIG_COMMANDS depfiles" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
@@ -21104,6 +21132,8 @@ s,@WITH_FFMPEGCOMPONENTS_TRUE@,$WITH_FFMPEGCOMPONENTS_TRUE,;t t
 s,@WITH_FFMPEGCOMPONENTS_FALSE@,$WITH_FFMPEGCOMPONENTS_FALSE,;t t
 s,@WITH_ALSACOMPONENT_TRUE@,$WITH_ALSACOMPONENT_TRUE,;t t
 s,@WITH_ALSACOMPONENT_FALSE@,$WITH_ALSACOMPONENT_FALSE,;t t
+s,@WITH_AUDIOEFFECTS_TRUE@,$WITH_AUDIOEFFECTS_TRUE,;t t
+s,@WITH_AUDIOEFFECTS_FALSE@,$WITH_AUDIOEFFECTS_FALSE,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
